version: "3.8"

networks:
  enchentes-net:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:16
    container_name: enchentes_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - enchentes-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: enchentes_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: America/Sao_Paulo
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - enchentes-net