services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=POSTGRES
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_DB=POSTGRES

    networks:
      - spring-cloud-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-cloud-network:
    driver: bridge